# Generated by Django 5.2.8 on 2025-11-21 18:47

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='ArchaeologicalSite',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('site', models.CharField(max_length=50)),
                ('city', models.CharField(max_length=50)),
                ('state', models.CharField(max_length=50)),
                ('country', models.CharField(max_length=50)),
                ('longitude', models.DecimalField(decimal_places=6, max_digits=9)),
                ('latitude', models.DecimalField(decimal_places=6, max_digits=9)),
            ],
        ),
        migrations.CreateModel(
            name='Collection',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('quantity_artefacts', models.PositiveIntegerField()),
            ],
        ),
        migrations.CreateModel(
            name='Localization',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('room', models.CharField(max_length=100)),
                ('shelf', models.CharField(max_length=100)),
                ('bookcase', models.CharField(max_length=100)),
            ],
        ),
        migrations.CreateModel(
            name='LogChanges',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('user', models.CharField(max_length=100)),
                ('change', models.IntegerField(choices=[(1, 'Create'), (2, 'Update'), (3, 'Delete')])),
                ('date_time', models.DateTimeField(auto_now_add=True)),
                ('reason', models.TextField()),
                ('table_name', models.CharField(max_length=50)),
                ('record_id', models.PositiveIntegerField()),
            ],
        ),
        migrations.CreateModel(
            name='RawMaterial',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=50)),
            ],
        ),
        migrations.CreateModel(
            name='Artefact',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('other_name', models.CharField(max_length=100)),
                ('dimension_length', models.PositiveSmallIntegerField()),
                ('dimension_width', models.PositiveSmallIntegerField()),
                ('weigth', models.PositiveIntegerField()),
                ('dating', models.PositiveSmallIntegerField(blank=True, null=True)),
                ('conservation_status', models.IntegerField(choices=[(1, 'Perfeito'), (2, 'Bom'), (3, 'Regular'), (4, 'Ruim'), (5, 'Critical'), (6, 'Irreversível')])),
                ('completeness', models.IntegerField()),
                ('description', models.TextField()),
                ('observation', models.TextField()),
                ('register_date', models.DateField(auto_now_add=True)),
                ('bibliographic_reference', models.TextField()),
                ('reserved', models.BooleanField(default=False)),
                ('archaeological_site', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='artefacts_as', to='core.archaeologicalsite')),
                ('collection', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='artefacts', to='core.collection')),
                ('localization', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='artefacts_localization', to='core.localization')),
                ('raw_material', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='artefacts_rm', to='core.rawmaterial')),
            ],
        ),
        migrations.CreateModel(
            name='ArtefactImage',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('public_id_cloudinary', models.CharField(max_length=100)),
                ('url_photo', models.CharField(max_length=255)),
                ('artefact', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='images', to='core.artefact')),
            ],
        ),
        migrations.CreateModel(
            name='ConservationAction',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('description', models.TextField()),
                ('date', models.DateField(auto_now_add=True)),
                ('artefact', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='conservation_actions', to='core.artefact')),
            ],
        ),
        migrations.CreateModel(
            name='Reserve',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('cpf', models.CharField(max_length=11)),
                ('email', models.EmailField(max_length=254)),
                ('phone', models.CharField(max_length=15)),
                ('artefact', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='core.artefact')),
            ],
        ),
        migrations.CreateModel(
            name='LogMovement',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('out_date', models.DateField()),
                ('return_date', models.DateField()),
                ('artefact', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='core.artefact')),
                ('reserve', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='core.reserve')),
            ],
        ),
        migrations.CreateModel(
            name='SubType',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=50)),
                ('raw_material', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='subtypes', to='core.rawmaterial')),
            ],
        ),
        migrations.AddField(
            model_name='artefact',
            name='sub_type',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='artefacts_st', to='core.subtype'),
        ),
    ]
