# Generated by Django 5.2.8 on 2025-11-21 13:04

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Image',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('public_id_cloudinary', models.CharField(max_length=100)),
                ('url_photo', models.CharField(max_length=255)),
            ],
        ),
    ]
