# Generated by Django 5.2.8 on 2025-11-21 19:49

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='archaeologicalsite',
            name='latitude',
        ),
        migrations.RemoveField(
            model_name='archaeologicalsite',
            name='longitude',
        ),
    ]
