# Generated by Django 5.2.8 on 2025-11-21 15:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0002_address_rawmaterial_subtype'),
    ]

    operations = [
        migrations.CreateModel(
            name='Localization',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('room', models.CharField(max_length=100)),
                ('shelf', models.CharField(max_length=100)),
                ('bookcase', models.CharField(max_length=100)),
            ],
        ),
        migrations.DeleteModel(
            name='Address',
        ),
    ]
