# Generated by Django 5.2.8 on 2025-11-21 20:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0003_artefact_collection_category_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='artefact',
            name='collection_category',
            field=models.IntegerField(choices=[(1, 'Arqueológico'), (2, 'Etnográfico'), (3, 'Paleontológico'), (4, 'Histórico'), (5, 'Bibliográfico'), (6, 'Documental'), (7, 'Indeterminado')], default=1),
        ),
        migrations.AlterField(
            model_name='artefact',
            name='completeness',
            field=models.IntegerField(choices=[(1, 'Inteiro'), (2, 'Fragmentado'), (3, 'Fraturado')], default=1),
        ),
        migrations.AlterField(
            model_name='artefact',
            name='conservation_status',
            field=models.IntegerField(choices=[(1, 'Perfeito'), (2, 'Bom'), (3, 'Regular'), (4, 'Ruim'), (5, 'Critical'), (6, 'Irreversível')], default=1),
        ),
        migrations.AlterField(
            model_name='artefact',
            name='detail_conservation_status',
            field=models.IntegerField(choices=[(1, 'Friável'), (2, 'Erodido'), (3, 'Lascado'), (4, 'Incompleto'), (5, 'Alterado quimicamente'), (6, 'Deformado'), (7, 'Estável')], default=1),
        ),
        migrations.AlterField(
            model_name='artefact',
            name='ethnic_group',
            field=models.IntegerField(choices=[(1, 'Sambaqui'), (2, 'Guarani'), (3, 'Itararé/Taquara'), (4, 'Indeterminado')], default=1),
        ),
        migrations.AlterField(
            model_name='artefact',
            name='technique',
            field=models.IntegerField(choices=[(1, 'Percussão'), (2, 'Lasqueamento por pressão'), (3, 'Abrasão / Polimento'), (4, 'Perfuramento'), (5, 'Entalhe'), (6, 'Raspagem'), (7, 'Retoque'), (8, 'Friccionamento'), (9, 'Não identificada')], default=1),
        ),
    ]
