# Generated by Django 5.2.8 on 2025-11-22 04:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0004_alter_artefact_collection_category_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='artefact',
            name='id',
            field=models.IntegerField(primary_key=True, serialize=False),
        ),
    ]
