# Generated by Django 5.2.8 on 2025-11-22 05:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0005_alter_artefact_id'),
    ]

    operations = [
        migrations.AlterField(
            model_name='artefact',
            name='bibliographic_reference',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='artefact',
            name='observation',
            field=models.TextField(blank=True, null=True),
        ),
    ]
