# Generated by Django 5.2.8 on 2025-11-21 18:06

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0003_archaeologicalsite'),
        ('core', '0005_origin'),
    ]

    operations = [
    ]
