# Generated by Django 5.2.8 on 2025-11-21 18:06

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0006_merge_0003_archaeologicalsite_0005_origin'),
    ]

    operations = [
        migrations.CreateModel(
            name='Artefact',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('other_name', models.CharField(max_length=100)),
                ('dimension_length', models.PositiveSmallIntegerField()),
                ('dimension_width', models.PositiveSmallIntegerField()),
                ('weigth', models.PositiveIntegerField()),
                ('dating', models.PositiveSmallIntegerField(blank=True, null=True)),
                ('conservation_status', models.IntegerField(choices=[(1, 'Perfeito'), (2, 'Bom'), (3, 'Regular'), (4, 'Ruim'), (5, 'Critical'), (6, 'Irreversível')])),
                ('completeness', models.IntegerField()),
                ('description', models.TextField()),
                ('observation', models.TextField()),
            ],
        ),
        migrations.CreateModel(
            name='LogMovement',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('out_date', models.DateField()),
                ('return_date', models.DateField()),
                ('artefact', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='core.artefact')),
            ],
        ),
    ]
