# Generated by Django 5.2.8 on 2025-11-21 18:14

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0007_artefact_logmovement'),
    ]

    operations = [
        migrations.CreateModel(
            name='Reserve',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('cpf', models.CharField(max_length=11)),
                ('email', models.EmailField(max_length=254)),
                ('phone', models.CharField(max_length=15)),
                ('artefact', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='core.artefact')),
            ],
        ),
        migrations.AddField(
            model_name='logmovement',
            name='reserve',
            field=models.ForeignKey(default=0, on_delete=django.db.models.deletion.PROTECT, to='core.reserve'),
            preserve_default=False,
        ),
    ]
