# Generated by Django 5.2.8 on 2025-11-21 17:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0007_artefact_conservationaction'),
    ]

    operations = [
        migrations.CreateModel(
            name='LogChanges',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('user', models.CharField(max_length=100)),
                ('change', models.IntegerField(choices=[(1, 'Create'), (2, 'Update'), (3, 'Delete')])),
                ('date_time', models.DateTimeField(auto_now_add=True)),
                ('reason', models.TextField()),
                ('table_name', models.CharField(max_length=50)),
                ('record_id', models.PositiveIntegerField()),
            ],
        ),
        migrations.RemoveField(
            model_name='conservationaction',
            name='artefact',
        ),
        migrations.DeleteModel(
            name='Artefact',
        ),
        migrations.DeleteModel(
            name='ConservationAction',
        ),
    ]
